### PR TITLE
[widgets] Allow case insensitive #diff

### PR DESCRIPTION
**Pull request by adsteel**
Addressing issue https://github.com/mojotech/dill/issues/17 and, potentially, https://github.com/mojotech/dill/issues/46

Reopened from: https://github.com/mojotech/dill/pull/115

### CODE REVIEW

**Comment by adsteel** [comment]
@david All great points. I've removed the values classes and implemented the private methods instead. You had one comment I did not address, regarding downcasing the Hashes separately:

"Would it be possible to skip this and always convert hashes to arrays?"

I played with that, but when a table comes back as an array of arrays when an array of hashes is expected, I couldn't get it to work:

```ruby
# this works
[{"name"=>"guybrush threepwood", "protagonist"=>"yes", "selected_item"=>"wimpy little idol"}]

# this does not
[["name", "guybrush threepwood"], ["protagonist", "yes"], ["selected_item", "wimpy little idol"]]
```

**Comment by david** [comment]
@adsteel could you tell me why the second case doesn't work? When is an array of hashes expected?

**Comment by adsteel** [comment]
@david A form's #to_table method returns an array of hashes, one for each row. I could replace the #downcase_hash method with something like this, but I'm not sure it's much better:

```
      def downcase_to_table(to_table)
        headers = to_table.first.keys
        rows = to_table.map { |row| row.values.map(&:downcase) }

        rows.prepend(headers)
      end
```

**Comment by david** [comment]
Alright, I think it's fine to leave it as is for now. :shipit:

**Pull request merged**
